name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: "1.0.0"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        shell: pwsh
        run: |
          msbuild FrpManager.sln /p:Configuration=Release /p:Platform=x86 /v:m

      - name: Prepare Assets
        shell: pwsh
        run: |
          $exePath = "Release\FrpManager.exe"
          if (Test-Path $exePath) {
              Copy-Item $exePath -Destination ".\FrpManager.exe"
              Compress-Archive -Path $exePath -DestinationPath ".\FrpManager.zip"
          } else {
              throw "EXE not found"
          }

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: |
            .\FrpManager.zip
            .\FrpManager.exe
          allowUpdates: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
